import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import type { Metadata } from "next";
import { strings as s } from "./constants";

export const metadata: Metadata = {
  title: "Misha Reyes",
  description: "Generated by NextJS + TailwindCSS + Sanity",
};

type navItemProps = {
  href: string;
  text: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  const NavItem = ({ href, text }: navItemProps) => {
    return (
      <li>
        <a
          href={href}
          className="flex text-xl hover:text-white active:text-background transition ease-in-out 
                duration-300 active:underline decoration-dotted decoration-[3px]">
          {text}
        </a>
      </li>
    );
  };

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body className="bg-background">
        <nav className="bg-nav sticky top-0 w-full flex flex-wrap border-b-2 border-black justify-between backdrop-blur-sm">
          <a href="#">
            <h2
              className={`p-2 px-6 duration-300 hover:drop-shadow-xl hover:text-white active:text-background`}>
              {s.misha.toLowerCase()}
            </h2>
          </a>
          <ul id="navlist" className="flex flex-row gap-6 self-center px-6">
            <NavItem href="#about-me" text={s.aboutMe} />
            <NavItem href="#projects" text={s.projects} />
            <NavItem href="#designs" text={s.designs} />
            <NavItem href="#contact" text={s.contact} />
          </ul>
        </nav>
        <div className="bg-background">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
