import "../globals.css";
import type { Metadata } from "next";
import { Navbar } from "./components";

export const metadata: Metadata = {
  title: "Misha Reyes",
  description: "Generated by React + NextJS + TailwindCSS",
  icons: "/icon.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <body className="bg-background">
        <Navbar />
        <div className="bg-background">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
